knife4j:
  enable: true
  setting:
    enable-version: true
spring:
  datasource:
    url: jdbc:mysql://localhost:36666/pism_benu?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  pmnx:
    cache-prefix: demo
    env: dev
  data:
    redis:
      port: 36379
      host: 127.0.0.1
      password: 123456
  aop:
    proxy-target-class: true
  cache:
    type: redis
    redis:
      use-key-prefix: false
logging:
  level:
    cn.com.pism.phoenix.core.mapper: debug

